### ISSUE TITLE
fetchNum() method

### ISSUE THREAD

**Issue by gholol** [auraphp/Aura.Sql#101]
Hi

It's not really an issue, just a simple question.
I'm little surprised that there's no fetchNum() method. Do you have any plans of implementing it?

**Comment by harikt** [comment]
You mean `PDO::FETCH_NUM` ?

**Comment by pmjones** [comment]
Not sure what you mean here @gholol -- can you expand a bit?

**Comment by gholol** [comment]
Well,  sure guys.

Aura.Sql provides fetchAssoc() method.

We can use it like this

```
$result = $pdo->fetchAssoc($stm, $bind);
```

Now, this of course retrieves an ASSOCIATIVE array (where the key is the
first column, and the row arrays are keyed on the column names), and so,  I cannot use it with list() function, because list() works only with numeric arrays.

I can do a workaround around this, and write something like:

```
$result = $pdo->fetchAssoc($stm, $bind);
list($value1, 
     $value2,
     $value3
) = array_keys($result);
```

But isn't it a bit impractical? Do you have any plans of implementing a function that returns a result as numeric array? (PDO:FETCH_NUM

**Comment by pmjones** [comment]
This particular case ...

``` php
$result = $pdo->fetchAssoc($stm, $bind);
list($value1, 
     $value2,
     $value3
) = array_keys($result);
```

... might be addressed by:

``` php
$values = $pdo->fetchCol($stm, $bind);
```

That will populate `$values` with the first column of all rows in the result set. (Note that `fetchAssoc()` uses the first column as the array key.)

Is that sufficient, or is there another case that needs to be addressed?

**Comment by pmjones** [comment]
@gholol Any further thoughts?

**Comment by gholol** [comment]
Hi!

Sorry for not responding, i was at work.

Your suggestion to use fetchCol() was right, it works perfectly ;) So i don't have anything else to rant about.

Have a nice day guys!
