### ISSUE TITLE
How to catch connection exceptions?

### ISSUE THREAD

**Issue by funkymunkey** [auraphp/Aura.Sql#102]
How I can catch thrown  excepion, e.g related to  MySQL server being offline?
I'm experiencing this problem only with this package. It looks like exceptions thrown in ExtendedPdo aren't being catched? or i'm just doing it wrong?

I tried to wrap it inside try...catch block at the very beginning of my php scripts.

```
try {
    $dbh = new Sql\ExtendedPdo(
        'mysql:host='.GameConfig::$DB_HOST.';dbname='.GameConfig::$DB_DATABASE.'',
        GameConfig::$DB_USER,
        GameConfig::$DB_PASSWORD
    );
} catch(PDOException $e) {
   //do stuff
}
```

But it still shows me this error:

```
 *Uncaught* exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Connection refused' in /home/grayfox/www/extel/vendor/aura/sql/src/ExtendedPdo.php:218 Stack trace: #0 
```

**Comment by pmjones** [comment]
That looks like it _should_ work. Is that code in a namespace? Maybe try catching `\PDOException` (note the leading backslash) if so.

**Comment by funkymunkey** [comment]
No, It's not inside any namespace. I'll make a clean project with composer and Aura/Sql and check if it works then.

**Comment by funkymunkey** [comment]
Okay, so after forcing connection inside try block

```
try {
    $dbh = new Sql\ExtendedPdo(
        'mysql:host='.GameConfig::$DB_HOST.';dbname='.GameConfig::$DB_DATABASE.'',
        GameConfig::$DB_USER,
        GameConfig::$DB_PASSWORD
    );
    $dbh->connect();
} catch(PDOException $e) {
   //do stuff 
}
```

It now catches exceptions correctly... I guess it was related to lazy loading.
I'll close this issue now. Thanks

**Comment by pmjones** [comment]
Oh of course it's the lazy loading. I should have thought of that. Good catch.
