### ISSUE TITLE
Parameter extraction is wrong with some SQL syntax

### ISSUE THREAD

**Issue by JLacoude** [auraphp/Aura.Sql#104]
Using PostgreSQL at least three different cases of SQL keywords are considered parameters.

First is the cast operator "::"

`$pdo->perform('SELECT 1::TEXT', ['someparameter' => 'b']);`
This one can be avoided using the verbose way to cast but the short syntax looks better.
The problem comes from https://github.com/auraphp/Aura.Sql/blob/2.x/src/Rebuilder.php#L159 for which a quick fix could be `"/[^:]+(:[a-zA-Z_][a-zA-Z0-9_]*)|(\?)/m"`

Second one is using colons in comments:
`$pdo->perform('
        -- :should not be replaced
        SELECT 1', ['someparameter' => 'b']);`
`$pdo->perform("
        /* :should not be replaced */
        SELECT '2'", ['someparameter' => 'b']);`

The third problem comes with the new jsonb operators: ?, ?| and ?& 

`$pdo->perform('SELECT CAST(\'{"a":1, "b": 2, "c": 3}\' AS JSONB) ? \'b\'', ['someparameter' => 'b']);`

This third one can hardly be fixed by the user.

I think the best way to handle those cases and I'm sure a lot more with other RDBMS would be to not use regular expressions to parse the query but a simple state machine. And have one per driver.

**Comment by pmjones** [comment]
Thanks for the report; extracting the params is a tricky business. I'm happy, but surprised, that there have been so few reports on this over the lifetime of that particular bit of code (10 years or so old by now).

> [do] not use regular expressions to parse the query but a simple state machine

/me nods

This sounds like a contribution candidate; if you can come up with one I'll review it.

**Comment by pmjones** [comment]
This appears to be fixed by #138
