### ISSUE TITLE
Typo in ReadMe?

### ISSUE THREAD

**Issue by mizterp** [auraphp/Aura.Sql#105]
Is this a typo?

| Current line | Fixed? |
| --- | --- |
| $bind = array('foo' => 'bar', 'baz' => 'dib'); | $bind = array('foo' => 'baz', 'bar' => 'dib'); |

**Comment by pmjones** [comment]
Yes, a typo. Send a PR with a fix and you'll get credit automatically.

**Comment by mizterp** [comment]
Done :)
