### ISSUE TITLE
instanceof Aura\Sql\Select

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Sql#11]
How do you convert instanceof `Aura\Sql\Select` ? The method `toString()` is protected . `__toString()` works when we try to `echo` or `print` the object .
I was passing a select object to the query. I think we need to change the protected method to public.

**Comment by guweigang** [comment]
It was ok to me... 

It is worth noting that before PHP 5.2.0 the __toString() method was only called when it was directly combined with echo or print. Since PHP 5.2.0, it is called in any string context (e.g. in printf() with %s modifier) but not in other types contexts (e.g. with %d modifier)

**Comment by harikt** [comment]
There was some issue . I guess this has been fixed by https://github.com/auraphp/Aura.Sql/commit/ca687febc38f9e58701c52a33f1f72bf557ffdcc 

And thank you @cnwggu .
