### ISSUE TITLE
yield with fetch*() functions

### ISSUE THREAD

**Issue by pavarnos** [auraphp/Aura.Sql#110]
# Hi Paul. Interested in your opinion on the value of using generators to reduce the memory footprint / increase performance. http://php.net/manual/en/language.generators.syntax.php eg fetchAssoc()

``` php
        // ...
        while ($row = $sth->fetch(self::FETCH_ASSOC)) {
            $key = current($row);
            yield $key => call_user_func($callable, $row);
        }
```

**Comment by iansltx** [comment]
I'm not @pmjones but I've thought about building something that implemented ExtendedPdoInterface but used async mysqli under the covers for result sets, which is somewhat in the same vein, and would likely use generators like you're doing here.

Catch of course is that we'd lose PHP 5.3 support, but seeing as how it's been EOL for ages, that's probably fine.

To clerify...I'm in favor of this for the next major release.

**Comment by Sieg** [comment]
Hi. And if possible, when the release is planned ? :)

**Comment by harikt** [comment]
Hey @Sieg ,

Major means 3.x . Currently it is not yet started for this package.

**Comment by Sieg** [comment]
@harikt, yes,

> To clerify...I'm in favor of this for the next major release.

Im interested in next major release date. Is it known already? This year summer, winter? next year ? :) As i see by commits history, the development of component is going not too fast?

**Comment by harikt** [comment]
@Sieg Sorry, I don't know more about the release dates / plans. And it will be hard to maintain different versions and dump old versions just for yield functionality. And we don't have many developers here to maintain all these versions. So time is a constraint. Anyway things will be here eventually as far as this is not a bug, but a feature.

Thank you.

**Comment by Sieg** [comment]
@harikt, thanks for the answer! The feature could be huge performance improvement for this layer. If you want more interest in your product, you should definitely introduce the implementation of generator usage in here ;) as soon as possible! Have a nice day!

**Comment by harikt** [comment]
@Sieg cool, thanks for your interest. If anyone is interested I can create a 3.x branch. So can send PR against 3.x.

I would also love and let @pmjones take care rest of the things.

Thank you

**Comment by pavarnos** [comment]
Just thinking out loud: the functions we are talking about are quite complex because of the optional callback passed in as a parameter. If there is going to be a new major release, why not drop the callback parameter to simplify things, and recommend lstrojny/functional-php for post processing results.

http://markbakeruk.net/2016/01/19/a-functional-guide-to-cat-herding-with-php-generators/ has an interesting article on making map/filter functions work for yield. It seems to me like the optional callback should be a post-processing step rather than an integral part of this package.

**Comment by pavarnos** [comment]
hmmm... my bad for not understanding clearly how this would be used. I tried rewriting fetchAll() with a yield

``` php
    public function fetchAll(
        $statement,
        array $values = array(),
        $callable = null
    ) {
        $sth = $this->perform($statement, $values);
        $rowCount = 0;
        while ($row = $sth->fetch(self::FETCH_ASSOC)) {
            if ($callable) {
                $row = call_user_func($callable, $row);
            }
            yield $rowCount++ => $row;
        }
    }
```

but get 20 failing tests because fetchAll() is supposed to return the entire data set as an array (not an Iterator).

Best alternative i can think of is to create a new function

``` php
    public function fetchIterator($statement,array $values = array()) {
        $sth = $this->perform($statement, $values);
        $rowCount = 0;
        while ($row = $sth->fetch(self::FETCH_ASSOC)) {
            yield $rowCount++ => $row;
        }
    }
```

and a related fetchIteratorObjects().

Would that work?

**Comment by harikt** [comment]
@pavarnos cool. Good experiments.

I am ok with adding a new functionality for newer things can be added and is not a BC issue. We can always push to major release. And probably document that this only works for php 5.x sort.

But we need to know what @pmjones thinks about the idea.

**Comment by pmjones** [comment]
I think it might be time to consider a 3.x branch. :-)

**Comment by pmjones** [comment]
All right, 3.x is started. @pavarnos, I say we drop the callable argument from the various `fetch*()` methods, and add new methods called `yield*()` that mimic the relevant `fetch*()` ones, to indicate they are generators. (Or perhaps `generate*()` ?)

**Comment by pmjones** [comment]
This is completed in the 3.x branch.
