### ISSUE TITLE
Binding variables conflicts with some Postgres SQL queries.

### ISSUE THREAD

**Issue by dhrrgn** [auraphp/Aura.Sql#111]
Assume you are trying to execute the following SQL query.

```
SELECT id
FROM users
WHERE created_at >= ':createdDate 00:00:00'::TIMESTAMP
  AND created_at <= ':createdDate 23:59:59'::TIMESTAMP
```

The `::type` syntax, in Postgres, casts the value to that `type` (above we are converting the string to a `TIMESTAMP`).  Now, lets try to execute the query and bind a value:

```
$conn->fetchAll($sql, ['createdDate' => '2015/12/01']);
```

This gives you an error: "Undefined offset: 0" in `src/Rebuilder.php` on line 247.

**Comment by pmjones** [comment]
Can you tell if #108 would resolve that?

**Comment by pmjones** [comment]
Alternatively, would it be enough to have the interpolator ignore `::` in what would otherwise be recognized as placeholders?

**Comment by dhrrgn** [comment]
I can't tell just by looking at that particular PR (it is rather massive).  Your second suggestion would probably be the best solution.  I am not sure how the interpolator works (haven't looked), but it should be something equivalent to this regexp: `:([\w.\-]+)` (not sure if you want to allow periods and hyphens).

**Comment by pmjones** [comment]
(/me nods) The code in question is in Rebuilder::rebuildPart(). If you want to submit a PR with a test I'll be happy to review, otherwise I'll come back around to this at some point in the future.

**Comment by dhrrgn** [comment]
I will see what I can do.  I won't be around this weekend, and don't have time to dig into it today, but I will take a look next week.

**Comment by dhrrgn** [comment]
Also, sorry, I totally missed #104 when looking through the open issues to see if this was mentioned anywhere.  I am actually just going to close this issue, and track that issue.  if I come up with an easier solution than that _massive_ pull request, I will submit that.

**Comment by pmjones** [comment]
@dhrrgn Revisiting this after a long hiatus;  this should be fixed on the 2.x branch now. Sorry for the very extended delay.
