### ISSUE TITLE
ExtendedPdoInterface missed method

### ISSUE THREAD

**Issue by vv3d0x** [auraphp/Aura.Sql#121]
Please provide in ExtendedPdoInterface method called "fetchGroup" that method does not exist in interface, ConnectionLocator return a ExtendedPdoInterface object and IDE does not support "fetchGroup" method (does not highlight)

**Comment by pmjones** [comment]
I hear you. Unfortunately, we can't modify the interface without breaking BC, which in turn requires a major version bump (from 2.x to 3.x).

However, we have started on the 3.x version, which may be of interest to you.

Sorry for the hassle.
