### ISSUE TITLE
Consider dropping arrays from quote()

### ISSUE THREAD

**Issue by pmjones** [auraphp/Aura.Sql#123]
ExtendedPdo::quote() converts arrays to comma-separated quoted values. Consider dropping this as a function of quote(), while leaving an equivalent in place for the Rebuilder.

**Comment by frederikbosch** [comment]
Or add a new method for it: `quoteArray` and `quoteScalar`. I would leave `quote` to its current behaviour.

**Comment by pmjones** [comment]
>  I would leave quote to its current behaviour.

Yeah, on consideration, that's the best thing. Thanks for the feedback!
