### ISSUE TITLE
Add statement iterator

### ISSUE THREAD

**Issue by aik099** [auraphp/Aura.Sql#125]
Currently the `fetchAll` can be used to get all data from statement execution as an array. This unfortunately will result in out of memory error, when:
- there is a lot of data
- consumer of data needs only 1 row at a time to process it

Proposing to add several iterators, that would:
1. accept `PDOStatement` in constructor
2. while used will emulate output of `fetchAll`, `fetchAssoc` or even `fetchCol`

I've created them for a FOSS project of mine, but why not having something like this built-in in this great package.

Related Resources:
- http://qa.in-portal.org/diffusion/INP/browse/branches%252F5.2.x/in-portal/branches/5.2.x/core/kernel/db/db_connection.php;16347$1238-1519
- http://www.dragonbe.com/2015/07/speeding-up-database-calls-with-pdo-and.html

**Comment by harikt** [comment]
Hi @aik099 , 

We have a 3.x branch coming which contains yield statement. https://github.com/auraphp/Aura.Sql/blob/a0542e6c5f45eb75c2122393fca7b92fe8589832/src/AbstractExtendedPdo.php#L610 . Hope that helps to fix the huge memory issue if any.

**Comment by pmjones** [comment]
Yes, @harikt has it right -- would the 3.x branch suit your needs @aik099 ?

**Comment by aik099** [comment]
It would if the minimal PHP version requirement was the same as for 2.x branch (PHP 5.3+). I'm using PHP 5.4 and therefore it doesn't help me at all.

**Comment by pmjones** [comment]
/me nods

There's a further problem: we can't change the 2.x ExtendedPdoInterface, because that would be a BC break. However, if you want to submit a PR with the iterators you mention as part of just ExtendedPdo (in the 2.x branch), I'll review it.

**Comment by harikt** [comment]
@aik099 if your app works fine in 5.3 + is there any issues upgrading it for 5.4 has become EOL iirc.

**Comment by aik099** [comment]
> There's a further problem: we can't change the 2.x ExtendedPdoInterface, because that would be a BC break. However, if you want to submit a PR with the iterators you mention as part of just ExtendedPdo (in the 2.x branch), I'll review it.

I'll see what I can do. Iterators won't require any change in the interface, because they would work with `->prepare` method result, which is PDOStatement class object. Without iterators large data transformations without lots of copy/pasted code aren't really possible for me unfortunately.

> @aik099 if your app works fine in 5.3 + is there any issues upgrading it for 5.4 has become EOL iirc.

@harikt , I'm using Aura.Sql not for a website project. This is a CLI app, that runs on developer machine and has access to SQLite database. Unfortunately I'm not able to guarantee that PHP version on each developer machine, where app is used would be 5.6 as 3.x branch demands.

**Comment by pmjones** [comment]
@aik099 Maybe I misunderstood. You want to create _new_ methods that return iterators, or _change_ the existing `fetch*()` methods to use iterators? If the former, all is well; if the latter, that's a non-starter.

**Comment by harikt** [comment]
Sure. Thank you.

**Comment by aik099** [comment]
> @aik099 Maybe I misunderstood. You want to create new methods that return iterators, or change the existing fetch*() methods to use iterators? If the former, all is well; if the latter, that's a non-starter.

I wanted to create new iterator classes, that would accept PDOStatement. No new methods, that return iterators would be added to the `ExtendedPdoInterface`, because you said before this would introduce a BC break.

**Comment by aik099** [comment]
If you allow to add new methods to the interface, then it's even better. In either case I don't plan to change signature of existing interface methods, because this would be a BC break for sure.

**Comment by pmjones** [comment]
Well, you can add the new methods to the `ExtendedPdo` _class_, but they cannot be part of the `ExtendedPdoInterface` (which I think is a fair tradeoff for the extra functionality). Changing the return of the existing `fetch*()` methods is a much more serious break, which is why it's a non-starter.

**Comment by aik099** [comment]
What if I add same `yield*` methods as in https://github.com/auraphp/Aura.Sql/blob/a0542e6c5f45eb75c2122393fca7b92fe8589832/src/AbstractExtendedPdo.php#L610, but they would return corresponding iterator instead?

If methods are used directly in `foreach`, then nobody will notice any difference.

**Comment by harikt** [comment]
@aik099 that breaks the minimum php version you mentioned https://github.com/auraphp/Aura.Sql/issues/125#issuecomment-212926907 . And yield is already coming in v3 . So probably you can send to 3.x branch .

**Comment by aik099** [comment]
No I'm mean this:

``` php
public function yieldAll($statement, array $values = array())
{
    $sth = $this->perform($statement, $values);

    return new AllPDOStatementIterator($sth);
}
```

This way people using `yieldAll` in 2.x version can continue use it in 3.x version without knowing that internally it does different things with same outcome.

**Comment by pmjones** [comment]
@aik099 I think that would be OK. If you want to submit a PR then I can review. Thanks!

**Comment by aik099** [comment]
I've already created iterators and just need write unit tests for them. If no problems will happen in the process then I should be able to submit PR this week.

**Comment by harikt** [comment]
@pmjones doesn't the build of 5.4 will fail in that case? Or do you think we document the change ?

**Comment by aik099** [comment]
> @pmjones doesn't the build of 5.4 will fail in that case? Or do you think we document the change ?

@harikt , why it should fail? I'm using 100% PHP 5.3 compatible syntax there.

**Comment by pmjones** [comment]
@harikt Unless I'm missing something, returning an iterator from function isn't a break. As long as it's not added to the interface, all should be well. Have I forgotten something?

**Comment by harikt** [comment]
oh oh sorry guys. I thought this uses `yield` function. Carry on :+1:  .

@aik099 thank you for clarifying.

**Comment by aik099** [comment]
PR created and ready for review: #127
