### ISSUE TITLE
Adding "$options" to "ExtendedPdo::perform" and "ExtendedPdo::prepareWithValues" methods

### ISSUE THREAD

**Issue by aik099** [auraphp/Aura.Sql#126]
The `ExtendedPdo::perform` method is allowing to specify created `PDOStatement` options. The `ExtendedPdo::prepareWithValues` (called directly or through `ExtendedPdo::perform` method) however doesn't allow specifying `$options` for underlying call to `ExtendedPdo::prepare` method.

This makes it impossible to create `PDOStatement` with custom options and bind values to it using Rebuilder in single `ExtendedPdo::prepareWithValues` method call.

Adding the `, $options = array()` parameter to both `ExtendedPdo::prepareWithValues` and `ExtendedPdo::perform` method (and to the `ExtendedPdoInterface`) should do the trick.

Related to #125.

**Comment by pmjones** [comment]
If you have the time and inclination, submit PR against the 3.x branch with this addition, and I can review it. (The PR would need to change the ExtendedPdoInterface as well.)

**Comment by pmjones** [comment]
@aik099 Any further interest in this? If so, a PR is welcome.

**Comment by aik099** [comment]
At the time I was suggesting this I thought it was needed to create `yield...` method-related iterators to be able to traverse over SQL result in both forward and backward (the `PDO::CURSOR_SCROLL` option). At the end iterators were implemented with default options to allow traversing forward only and that's why this was never needed.

Not sure if I'll submit this PR any time soon.

**Comment by pmjones** [comment]
> At the end iterators were implemented with default options to allow traversing forward only and that's why this was never needed.

Good enough. If you find a need, please re-open as you find convenient. Thanks!
