### ISSUE TITLE
Write SQLs can be queried in fetch* methods

### ISSUE THREAD

**Issue by guweigang** [auraphp/Aura.Sql#13]
$strsql_w = "insert into `rel_rev_file` (revid, fileid, addtime, modtime)  values (333, 9, '2012-04-24 16:00:00', '00-00-00 00:00:00')";

$sql->fetchAll($strsql_w);

it do insert record into table rel_rev_file and throw an exception like this:

[25-Apr-2012 07:41:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY0
00]: General error' in /home/guweigang/local/httpd/htdocs/cr-api/application/library/Crd/Sql/Adapter/Abst
ract.php:433
Stack trace:
#0 /home/guweigang/local/httpd/htdocs/cr-api/application/library/Crd/Sql/Adapter/Abstract.php(433): PDOSt

atement->fetchAll(2)
#1 /home/guweigang/local/httpd/htdocs/cr-api/application/controllers/Index.php(54): Crd_Sql_Adapter_Abstr

act->fetchAll('insert into `re...')
#2 [internal function]: IndexController->indexAction()
#3 /home/guweigang/local/httpd/htdocs/cr-api/index.php(7): Ap_Application->run()
#4 {main}

  thrown in /home/guweigang/local/httpd/htdocs/cr-api/application/library/Crd/Sql/Adapter/Abstract.php on
 line 433

**Comment by harikt** [comment]
Interesting one :) .

I tried for PDO also .

```
$stmt = $pdo->prepare( $text );
$stmt->execute();
$result = $stmt->fetchAll(PDO::FETCH_OBJ);
```

PDO also inserts data, but no error .

```
$text = "INSERT INTO `posts` (`author_id`, `title`, `body`)
    VALUES ('1', 'Hello World', 'Hello World');";
$sql->fetchAll( $text );
```

But for this it has, but I wonder why, for there is nothing other than the same statements are run. Though there is an exception data is inserted .

**Comment by guweigang** [comment]
hey, harikt

i have pushed my codes to https://github.com/cnwggu/Aura.Sql

So do you have time to review it? Waiting for your answer

**Comment by harikt** [comment]
@cnwggu , @pmjones is the right person to review it . I will also look into it , currently on a trip ;) .

**Comment by pmjones** [comment]
Interesting; it only generates an exception in MySQL; PostgreSQL and SQLite do not generate errors.

@cnwggu Is it your position that the `fetch*()` methods should prevent use of `INSERT`, `UPDATE`, etc.?

If so, it seems like the effort to do that is high in comparison to the reward.  It would be easier to say in documentation that "the `fetch*()` methods are convenience methods for retrieving data; using them for data manipulation may result in undefined behavior. Use the `query()`,  `insert()`, `update()`, etc. methods instead."

**Comment by guweigang** [comment]
@pmjones Yes, i agree.
