### ISSUE TITLE
try{} catch() {} for PDOException

### ISSUE THREAD

**Issue by melvinchia** [auraphp/Aura.Sql#130]
Hi, I'm writing a RESTful API application, and need to detect if a database goes off-line without the entire application bombing out with a PDOException.

I'm using Aura.Sql and Aura.SqlQuery, but how and where in the query do I incorporate a try{} catch() {} so that I can return a logical false before the application bombs out when using Aura.Sql as an ExtendedPdo?

**Comment by harikt** [comment]
@melvinchia I am not specifically sure what you are looking for.

You can use try catch before you execute the queries. It can be any query via pdo. If you came across any specific problem happy to hear.

Thank you.

**Comment by harikt** [comment]
@melvinchia was you able to solve this or still need some help?

If you were able to solve this, please close the issue.

Thank you.

**Comment by pmjones** [comment]
@melvinchia I suggest wrapping the actual ExtendedPdo call from Aura.Sql to begin with.

``` php
try {
    $all = $pdo->fetchAll('SELECT * FROM foo');
} catch (Exception $e) {
    // something went wrong
}
```

Let us know if that helps or not, and we can reopen the ticket as needed.
