### ISSUE TITLE
AllIterator first is always empty.

### ISSUE THREAD

**Issue by cdekok** [auraphp/Aura.Sql#131]
When i iterate over the AllIterator (or other iterators) the first time the row will always be null.
because the first call is ->valid() and it checks for:

```
$this->row !== false
```

After it goes to the current method, then it will go to the next if we call the fetch on the valid method it should work properly.

**Comment by pmjones** [comment]
That sounds like a problem. The test, though, seems to show the right behavior (https://github.com/auraphp/Aura.Sql/blob/2.x/tests/AbstractExtendedPdoTest.php#L234-L241). Is the test put together incorrectly, maybe?

**Comment by aik099** [comment]
@cdekok , are you using `yield*` methods to create iterator or manually create it by using existing PDOStatement?

**Comment by cdekok** [comment]
I am using the yieldAll method but really it shouldn't matter the problem is in the iterator.
You can see the order for iterator calls on: http://php.net/iterator

```
rewinding
valid: 1
current: 1
key: 0
0: 1
next: 2
```

Am not sure why the test works though it seems to be ok?

**Comment by pmjones** [comment]
@cdekok If you can write a test for it, that shows the failure, that will help us track down the problem.

**Comment by aik099** [comment]
The `rewind` method is calling `next`, which in turn (for `AllIterator`) does `$this->row = $this->statement->fetch();`. So unless `PDOStatement::fetch` returns `null` instead of `false` for some reason it should work.

Maybe it works for SQLite (used during tests), but fails for MySQL. Which DB are you using?

**Comment by cdekok** [comment]
Ah yes you are right i totally missed it it works fine, it was because it was passed aync in guzzle seems that never hits rewind.
