### ISSUE TITLE
Profiler logs most queries twice

### ISSUE THREAD

**Issue by pavarnos** [auraphp/Aura.Sql#133]
call $xpdo->fetchAll('select * from my_table');
It calls perform() as below
```php
    public function perform($statement, array $values = [])
    {
        $this->connect();
        $sth = $this->prepareWithValues($statement, $values);
        $this->profiler->start(__FUNCTION__);
        $sth->execute();
        $this->profiler->finish($statement, $values);
        return $sth;
    }
```

prepareWithValues() also calls $this->profiler->start() and finish(), so each query gets two items in the log (unless you write a special logger filter to ignore one of them). Can you think of a good way around this from within ExtendedPDO? I can't at the moment...

I think the root of my discomfort with this is our earlier discussion about a ProfiledExtendedPDO. It seems wasteful to have 2 calls to a null profiler for every query when the majority of (production) use does not need logging at all.

**Comment by pmjones** [comment]
Agreed. I no longer think the "prepare" portion is worthy of logging, and it should be removed from 3.x. (Speaking of 3.x, I think the last major thing to deal with is the "rebuilder" logic from @JLacoude, which I mat attempt to address myself.)

**Comment by pavarnos** [comment]
sounds good. 
a 3.x release soon would be awesome. thanks!
while we are thinking about this... the logger logs the actual $statement object which makes using chrome-php a hassle: lots of clicks to open each log item to see what it actually is.

eg from Profiler.php near the bottom
```php
$profile['statement']   = $statement;
```
but the $statement parameter is declared as a string parameter. Maybe the line should be
```php
$profile['statement']   = $statement . '';
```
?
or maybe (since it is v3) do a string typehint to force the issue?

**Comment by harikt** [comment]
There was also a suggestion to show real sql query so we can just copy and paste the code that need to be executed. Currently if there is bind params it was showing differently.

**Comment by pavarnos** [comment]
Showing the full/final query sounds very handy

**Comment by frederikbosch** [comment]
@pavarnos This can be achieved as follows [starting with PHP 7.2](https://wiki.php.net/rfc/debugging_pdo_prepared_statement_emulation).

```php
<?php
$stmt->activeQueryString();
```

It could be used for logging.

**Comment by pmjones** [comment]
Fixed by https://github.com/auraphp/Aura.Sql/commit/3d07fdd25736cd9842f119fed772011510f22762
