### ISSUE TITLE
[3.x] Do not distribute password in exports

### ISSUE THREAD

**Issue by frederikbosch** [auraphp/Aura.Sql#135]
I would suggest implementing `__debugInfo` and `sleep` to prevent passwords showing up in logging or debugging information. You can have a look at [Halite](https://github.com/paragonie/halite) how this could be implemented: see their `HiddingString` class with the [__debugInfo](https://github.com/paragonie/halite/blob/master/src/HiddenString.php#L66) and [__sleep](https://github.com/paragonie/halite/blob/master/src/HiddenString.php#L112).

If people agree on this, I am happy to create a PR.

**Comment by harikt** [comment]
Hi @frederikbosch , 

I am sorry for I don't know what you are going to show in the debuginfo or using sleep ?

**Comment by frederikbosch** [comment]
@harikt Everything except the login credentials.

**Comment by pmjones** [comment]
Fixed in #137
