### ISSUE TITLE
Documentation on other functions than retrieve related

### ISSUE THREAD

**Issue by cdarken** [auraphp/Aura.Sql#136]
Hi. Do you plan to add some info how to use insert, update and transactions? Would be helpful.

**Comment by pmjones** [comment]
Hi @cdarken -- what did you have in mind?

**Comment by cdarken** [comment]
Hello @pmjones . I was able to look into the source and the tests to see how update and insert should be used, but I think that the README should be updated with some snippets for those cases as well, what do you think?

**Comment by harikt** [comment]
@cdarken feel free to send a PR with the changes you love to see.

Someone will review and merge it. We are always happy to accept PR.

Thank you.

**Comment by pmjones** [comment]
If someone wants to actually write the examples, that's cool with me; send a PR and I'll review. Closing this ticket until then; can re-open as needed.
