### ISSUE TITLE
Memory leak in mb_ereg (3.x-dev)

### ISSUE THREAD

**Issue by pavarnos** [auraphp/Aura.Sql#139]
There is a memory leak in https://github.com/auraphp/Aura.Sql/commit/c90d5e41737dfc37390261da2ebb58beadddf322#diff-b3a065d18dc02d1d5303063ecda9fc5bR330
if $this->statement is an object (like Aura\SqlQuery\Select).

`Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 951310208 bytes) in /var/www/mysite/vendor/aura/sql/src/Parser/State.php on line 335`

It needs to be casted to string at some stage much earlier (not sure where is best) eg mb_ereg_search_init((string) $this->statement) fixes the problem.

**Comment by pmjones** [comment]
Yet another reason to try and move away from mbstring, if at all possible.

**Comment by pmjones** [comment]
@jlacoude Any thoughts on this?

**Comment by pmjones** [comment]
@pavarnos In the mean time, casting to a string might be a worthwhile addition. Can you try for me, changing line 532 in AbstractExtendedPdo from this:

    $queries = $this->parser->rebuild($statement, $values);

To this: 

    $queries = $this->parser->rebuild((string) $statement, $values);

That should solve the object-related issue.

Let me know if that works!

**Comment by pmjones** [comment]
(Or, alternatively, put the cast into AbstractParser::rebuild(), or the Query constructor.)

**Comment by pavarnos** [comment]
heading out of the office for the next few days... won't have the chance to try. but as mentioned in the original comment `mb_ereg_search_init((string) $this->statement)` fixes it.

I agree with moving away from mb_ereg* because it looks like it keeps internal state and will not be thread safe if/when the PHP world moves to reactphp or similar.

**Comment by pmjones** [comment]
I believe mb_ereg has been removed entirely, as of #141, which resolves this specific issue. However, @pavarnos, if you want, I'm still happy to receive a PR that converts incoming objects to strings.

**Comment by pavarnos** [comment]
thanks. all my tests pass since this latest merge, so its looking good.
