### ISSUE TITLE
LIKE in query

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Sql#14]
How do you make a LIKE statement ?

`SELECT * FROM table WHERE {$column} LIKE :{$column}`

**Comment by pmjones** [comment]
Yes, and then you would bind `$data[$column] = '%$value%'` to the query.

**Comment by pmjones** [comment]
@harikt Does that solve it for you?

**Comment by harikt** [comment]
@pmjones Yes I guess. I will reopen if it doesn't work . 

It was for https://github.com/harikt/Hari.Blog/blob/master/src/Hari/Blog/ORM/DataSource/Db.php#L47
