### ISSUE TITLE
quoteIdentifier for tables / columns

### ISSUE THREAD

**Issue by cdekok** [auraphp/Aura.Sql#149]
it would be nice if the library would provide a way to escape tables / columns similar to the zf db adapter.

**Comment by harikt** [comment]
@cdekok you can use something like https://github.com/auraphp/Aura.SqlQuery

**Comment by cdekok** [comment]
@harikt Ah yes perhaps this issues should be in the query project as it already has the quoter object.
Unfortunately the getQouter method there is protected.
If i would like to do something like `$sql = 'create database ' . $db->quoteName('foo')` it's not possible without instantiating or overriding the queryFactory as far as I can see.

**Comment by pmjones** [comment]
@cdekok Would you find it sufficient to ...

    $quoter = new Aura\SqlQuery\Quoter('`', '`');

... and then use `$quoter` for your purposes?

**Comment by harikt** [comment]
@pmjones I have edited your answer to have FQNS. So easy to understand I believe. Else it took sometime to light my brain :-) .

**Comment by cdekok** [comment]
@pmjones Yeah this will work only I feel that this should only be instantiated once depending on which database you use.
Now I can still make my own database wrapper around it but as a user I would prefer the library takes care if this for me already.
Perhaps this would be a something which could be done in a Aura Db package which bundles the two libraries or having the quoter in a public interface in the sql query library?

**Comment by pmjones** [comment]
@cdekok In the 1.x version, there was a pretty sophisticated quoteIdentifier() system that would examine an SQL query for identifiers and then quote them automatically. In 2.x it was extracted to the SqlQuery library, as it seemed to make more sense having it there.

Having said that, I might be OK with bringing it back in the 3.x version, but only for the simplest possible case; that is, to quote a standalone name, not to search for names in SQL snippets. It would likely be part of the Parser classes, though with a convenience method at the ExtendedPdo level.

Does that sounds like it could be suitable for your purposes?

**Comment by cdekok** [comment]
Definitely it would just be a simple method to quote table names / columns in a way other libraries support too for example DBAL 
http://www.doctrine-project.org/api/dbal/2.5/source-class-Doctrine.DBAL.Connection.html#714-731
or ZF
https://framework.zend.com/apidoc/2.2/classes/Zend.Db.Adapter.Platform.Postgresql.html#quoteIdentifier
I wouldn't like to see any magic escaping.

**Comment by pmjones** [comment]
@cdekok Please review the new `quote-name` branch, targeted for the 3.x release, specifically this commit: https://github.com/auraphp/Aura.Sql/commit/03607a9e5abfe488f33961806d864ac2b947c666

Let me know if that suits your use case(s).

**Comment by pmjones** [comment]
@cdekok Any thoughts on the above commit?

**Comment by cdekok** [comment]
@pmjones sorry was a bit busy, it looks great by me and exactly what I needed. 
It's a shame we cannot just use the quoter from the SqlQuery though but I suppose splitting up the quoter in it's own library is perhaps a bit too much for something so simple.

**Comment by pmjones** [comment]
Merged in #153
