### ISSUE TITLE
getPDO() or getInnerPDO()?

### ISSUE THREAD

**Issue by pavarnos** [auraphp/Aura.Sql#150]
Can we have a getPDO() or getInnerPDO() method?

Would be very handy when using phpDebugBar and other libraries which have their own PDO decorator.
I have code that builds the PDO and DecoratedPdo in a nice small tidy method that works for any environment. Later on, in another galaxy far far away, we check to see if we are on a dev server or in debug mode or whatever. What I want to be able to do is:

```php
$originalPDO = $container->get(DecoratedPdo::class)->getPDO();
$traceablePDO = new DebugBar\DataCollector\PDO\TraceablePDO($originalPDO);
$container->set(DecoratedPdo::class, new DecoratedPdo($traceablePDO));
```

which slides the debug bar in between the original pdo and the decorated pdo

**Comment by pmjones** [comment]
Call it getPdo() and send a PR! :-)

**Comment by pmjones** [comment]
As a side note, is `DebugBar\DataCollector\PDO\TraceablePDO` typehinted on `PDO`? Because `ExtendedPdo` extends PDO directly, so a PDO typehint should work there.

**Comment by pavarnos** [comment]
Yes. see https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/DataCollector/PDO/TraceablePDO.php#L12

but the example code above was simplified quite a bit. I actually typehint against `class DatabaseConnection extends DecoratedPdo` because it makes stuff a lot clearer... long story... too boring to tell...
