### ISSUE TITLE
ProfilerInterface too broad?

### ISSUE THREAD

**Issue by pavarnos** [auraphp/Aura.Sql#157]
Is the Profiler interface is broader than it needs to be? AbstractExtendedPdo only calls `$profiler->start()` and `$profiler->finish()`. 

The other methods fall into two groups: 
- `setLogLevel()`, `getLogger()`, `getLogFormat()` belong to a profiler that implements a Psr\Log\LoggerInterface
- `setActive()`, `isActive()` belong to a profiler than can be switched on and off

AbstractExtendedPdo does not care about either of those implementation details.

**Comment by pmjones** [comment]
Maybe? But at the same time, I find myself using those things elsewhere, so I'm content to leave them in place. Do you have strong feelings about it one way or the other?

**Comment by pavarnos** [comment]
nope, no strong feelings. was just thinking through the interface when trying one of several ways to connect ExtendedPDO to phpDebugBar (which wraps a PDO) while also wrapping it in my own layer of convenience functions.
