### ISSUE TITLE
ExtendedPdo prepareWithValues error in MySQL

### ISSUE THREAD

**Issue by jelofson** [auraphp/Aura.Sql#158]
Was messing with Atlas and ran into the following mysql error.

We can use the usual scenario of threads, tags, and taggings in this example.

In atlas, if we try the following:

```php
$post = $atlas->fetchRecord(ThreadMapper::CLASS, 2, ['taggings', 'tags']);
```

If there are no associated tags for the post, then the query will fail (in mysql). Works in sqlite, so tests seem to pass.

What appears to happen is the 3rd query that is prepared will look something like this:
```
SELECT
    `tags`.`tag_id`,
    `tags`.`tag`
FROM
    `tags`
WHERE
    `tags`.`tag_id` IN ()
```
and MySQL will throw a syntax error (NOTE that sqlite does not return an error here)
```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 7 in /home/jelofson/www/atlas/vendor/aura/sql/src/ExtendedPdo.php:748
```
Ultimately, this comes back to the `ExtendedPdo::quote()`, but I don't know if I would call it a bug here, or if Atlas should not attempt to even run that query if there are no `taggings`. 

One method I used to temporarily fix it (really, just trying to debug), was to add this at the beginning of the `ExtendedPdo::quote()` method:

```
if (! $value) {
    return 'null';
}
```

And that will result in 

```
SELECT
    `tags`.`tag_id`,
    `tags`.`tag`
FROM
    `tags`
WHERE
    `tags`.`tag_id` IN (null)
```

Or, use 

```
if (! $value) {
    return "''";
}
```

And that will result in 

```
SELECT
    `tags`.`tag_id`,
    `tags`.`tag`
FROM
    `tags`
WHERE
    `tags`.`tag_id` IN ('')
```

Both those queries seem valid in MySQL and Sqlite.
This was in version 2, but applies to version 3 as well.

What do you think? Is this something to modify in Atlas, or in Aura\Sql?
I think Aura\Sql is doing what it is supposed to do, so maybe in Atlas?

**Comment by pmjones** [comment]
I think this is more in the realm of Atlas.

**Comment by jelofson** [comment]
@pmjones Ok, then I can close this and open a new issue in Atlas if you like...

**Comment by pmjones** [comment]
I think that's the most appropriate thing to do; many thanks! (I can already imagine the fix.)
