### ISSUE TITLE
sqlsrv can't use errmode_exception

### ISSUE THREAD

**Issue by auroraeosrose** [auraphp/Aura.Sql#159]
Long ago and far away (in 2015) there was a bug in pdo_sqlrv (see issue #90) which was fixed with a rather hacky detection of sqlsrv in the dsn string

However... it's 2017 and pdo_sqlsrv is long fixed (was fixed even before their github move) but the hacky workaround in code is breaking exception usage with the driver, you cannot set the error mode to exception using the extended pdo constructor

The hacky fix REALLY should be pulled back out 

I can happily do a PR for ripping the code back out ... right now I have a horrific copy and paste override constructor I'm maintaining just to remove the ick :(

Not sure what the best fix is though

**Comment by pmjones** [comment]
Thanks a ton for pointing this out, and sorry for the hassle. Think up a PR and send it along at your convenience. (And good to see you. :-)

**Comment by auroraeosrose** [comment]
I'm thinking that a note in the docs that you MUST set your error mode to non-exception if you're still on super old versions of the driver and get that obscure error + ripping the hack out would be the best fix

**Comment by pmjones** [comment]
I'm OK with that. Can you link me to which version (or when) the errmode_exception starting being valid? It would help with the docs.

Thanks for your patience.

**Comment by pmjones** [comment]
@auroraeosrose Wait, this hack-fix exists only in the 3.x branch, yes? If so, then seeing as there have been only alpha releases of 3.x, pulling it out is zero problem.
