### ISSUE TITLE
how to use Aura.Sql.Adapter.Abstract::update to auto increase field???

### ISSUE THREAD

**Issue by guweigang** [auraphp/Aura.Sql#16]
method declare:

```
public function update($table, array $cols, $cond, array $data = array())
```

if i want to increase `count` field by 1, i will use update() like this:

```
update("tbl_name", array('count' => 'count+1", "uid=1");
```

it will generate sql like: 

```
set count='count+1'
```

cause data type of field count  is "int", so it will convert 'count+1' to 0.

so what can i do?

**Comment by harikt** [comment]
So the problem is 

```
foreach ($cols as $col => $val) {
    $list[] = $this->quoteName($col) . " = :$col";
}
```

https://github.com/auraphp/Aura.Sql/blob/master/src/Aura/Sql/Adapter/AbstractAdapter.php#L876

Wondering what will be the best solution here .. @pmjones thoughts ?

**Comment by guweigang** [comment]
@harikt maybe i fixed it ... if $cols's key is int, then push it in $list directory, or else do it as before

```
      foreach ($cols as $col => $val) {
            if (is_int($col)) {
                $list[] = $this->quoteNamesIn($val);
            } else {
                $list[] = $this->quoteName($col) . " = :$col";
            }
        }

```

**Comment by harikt** [comment]
@cnwggu I feel its a wrong assumption .

```
// the table to update
$table = 'foo';
// the new column values to set
$cols = [
    'count' => "count + 1",
];
// a where condition to specify which rows to update
$cond = 'id = :id';
// additional data to bind to the query
$data = ['id' => 1];
// perform the update; result is number of rows affected
$result = $sql->update($table, $cols, $cond, $data);
```

See `$cols` is an associative array . And the key is not int . The one way I thought was search the value for keys like `count` . But that will not work out :) .

Aaah man , can you try like 

```
    // the new column values to set
$cols = [
    'count' => "`count` + 1",
];
```

Probably this will work out :) . Try and let me know, or I will look tonight .

**Comment by guweigang** [comment]
@harikt hi, you see 

```
$text .= implode(', ', $list);
```

It simply join $list with ",",  and strings like :$col will be replaced by $data. So I don't think $col must be an associative array.

It's key can be int. Even there are strings like :$col  in numeric-key array, it will also be replaced by $data. Most importantly, they will generate same sqls.

```
// the table to update
$table = 'foo';
// the new column values to set
$cols = [
  "`count`=`count` + 1",
  "`age`=:age",
  "name" => "cnwggu",
];
// a where condition to specify which rows to update
$cond = 'id = :id';
// additional data to bind to the query
$data = ['id' => 1, 'age' => 28];

// perform the update; result is number of rows affected
$result = $sql->update($table, $cols, $cond, $data);
```

Do you think so @pmjones ?

**Comment by harikt** [comment]
What I thought was add a search in `$val` within the `foreach` something like

```
foreach ($cols as $col => $val) {
    if ( search for count + ||  x + count in $val ) {
        $list[] = $this->quoteName($col) . " = $val";
        // Yes we should quote here.
    } else {
        $list[] = $this->quoteName($col) . " = :$col";
    }
}
```

But I still wonder whether there will be any other issues. Thoughts ? :-)

**Comment by guweigang** [comment]
If do like this, you will have to replace all fields before passing them in update...

but how can you know which field is needed to replace???

**Comment by guweigang** [comment]
@harikt this is very important.... today, i met this problem again...

i want to set "status=status | 0x10101", so it is a common issue.

**Comment by harikt** [comment]
@cnwggu I am sorry that I wasn't able to help you :( . I have been looking for a solution. But still not found :( . I can recognize your feelings as an early adopter . 

@pmjones can you please have a look, if you have a bit of time to spare?.

**Comment by harikt** [comment]
@cnwggu  for the time, may be you could run custom sql.

**Comment by harikt** [comment]
@pmjones  I have been trying this. I don't think this is fixed . 

Keeping the table and script for easiness 

SQL :

```
-- Adminer 3.3.3 MySQL dump

SET NAMES utf8;
SET foreign_key_checks = 0;
SET time_zone = 'SYSTEM';
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `count`;
CREATE TABLE `count` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `count` int(11) NOT NULL,
  `order` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO `count` (`id`, `count`, `order`) VALUES
(1, 0,  0);

-- 2012-07-08 09:43:20
```

PHP :

```
<?php
$adapter_factory = include '/path/to/Aura.Sql/scripts/instance.php';
$sql = $adapter_factory->newInstance(

    // adapter name
    'mysql',

    // DSN elements for PDO; this can also be
    // an array of key-value pairs
    'host=localhost;dbname=database_name',

    // username for the connection
    'username',

    // password for the connection
    'password'
);

// the table to update
$table = 'count';

// the new column values to set
$cols = [
    'count' => "count + 1",
];

// a where condition to specify which rows to update
$cond = 'id = :id';

// additional data to bind to the query
$data = ['id' => 1];

// turn on the profiler
$sql->getProfiler()->setActive(true);

// perform the update; result is number of rows affected
$result = $sql->update($table, $cols, $cond, $data);

foreach($sql->getProfiler()->getProfiles() as $i => $profile ) {
    echo "Query : " . ($i+1) . "  " . $profile->text . " took " . $profile->time . PHP_EOL;
    //print_r( $profile->trace );
}
```

**Comment by guweigang** [comment]
@harikt you should use $cols like this 
$cols = ['count=count+1']

**Comment by harikt** [comment]
@cnwggu no I don't think so . See examples in https://github.com/auraphp/Aura.Sql#modifying-rows .

**Comment by harikt** [comment]
Oh is it only one column ? If so we may want to update in documentation .

**Comment by guweigang** [comment]
@harikt no, you can use both integer and string as key:
$cols = ['count=count+1', 'order' => 5];

**Comment by harikt** [comment]
hm. I don't think so. Lets wait for @pmjones thoughts on this.

**Comment by pmjones** [comment]
What exactly is the problem?  You _should_ be able to do this:

```
$data = array(
    'colname' => 'some value',
    'count = count + 1',
);
```

Note that the second element is integer-indexed (even though it doesn't have the integer there). That means it's not a column name, and gets used as-is when doing the update.

**Comment by pmjones** [comment]
I'm not really happy about how the syntax looks, but it will do for now.  A future release will have Insert, Update, and Delete objects that work like the Select object does now.

**Comment by harikt** [comment]
aah ok fine :-) , may be we should document this or do you think we may break BC ?

**Comment by pmjones** [comment]
It's not a BC break, because the old way still works exactly as before.  This is a feature addition.  Yeah, adding it to the docs might be nice.
