### ISSUE TITLE
Invalid parameter count

### ISSUE THREAD

**Issue by php-** [auraphp/Aura.Sql#162]
Hello 

for the example query 
`SELECT * FROM users WHERE username = :user_name OR email = :user_name`
and setting 

`$select->bindValue('user_name', $username);`

Gives SQL wrong parameter number error. Problem is using one placeholder twice, I think this should not be a problem and it works for normal PDO statements

**Comment by harikt** [comment]
You may look into 3.x version .. https://github.com/auraphp/Aura.Sql/blob/695b240f1bd64dd5ba457935d7c0337be1055be5/docs/upgrade.md#repetition-of-named-placeholders . It is still not released as stable, but on betas.

**Comment by php-** [comment]
Alright, thanks!
