### ISSUE TITLE
getAttribute() pass-through calls do not work

### ISSUE THREAD

**Issue by AlexHowansky** [auraphp/Aura.Sql#163]
Using 3.0.0-beta1:
```
$db = new \Aura\Sql\ExtendedPdo(...);
$driver = $db->getAttribute(\PDO::ATTR_DRIVER_NAME);
```
This returns nothing and emits the following warning:
```
PHP Warning:  PDO::getAttribute(): SQLSTATE[00000]: No error: PDO constructor was not called in ...
```
Forcing a connect with the `connect()` method before calling `getAttribute()` does not work. I can work around the issue by doing this:
```
$driver = $db->getPdo()->getAttribute(\PDO::ATTR_DRIVER_NAME);
```
However, I don't believe this should be required, as the `getAttribute()` method should still work correctly in the extended class.

**Comment by harikt** [comment]
The problem why it is not working is mentioned on https://github.com/auraphp/Aura.Sql/pull/164#issuecomment-341367053 .

For the current time, as you can rely on the `getPdo` please make use of it.

Thank you.

**Comment by harikt** [comment]
Merged. So closing the same.
