### ISSUE TITLE
ExtendedPdoInterface missing yield methods

### ISSUE THREAD

**Issue by sunkan** [auraphp/Aura.Sql#168]
The ExtendedPdoInterface don't have any of the yield methods defined.

**Comment by pmjones** [comment]
Yeah; adding them to the interface would be a BC break, sadly.

**Comment by sunkan** [comment]
My bad it's Atlas that depends on 2.x branch

**Comment by pmjones** [comment]
Maybe add them as @method docblocks, so that IDE typehinting works even when they're not in the interface proper?

**Comment by sunkan** [comment]
yea that would work. can put together a pull request

**Comment by pmjones** [comment]
Thanks, and thanks for the attention you've given the project lately!

**Comment by sunkan** [comment]
I have been using Aura packages for years so I feel I need to give something back.

**Comment by pmjones** [comment]
Fixed via #169
