### ISSUE TITLE
Inserting NULL values?

### ISSUE THREAD

**Issue by dashifen** [auraphp/Aura.Sql#173]
This is probably the wrong place to ask this, though hopefully you can help.  I googled around and found a lot of information about working with the base PDO object and inserting (or updating) database cells to a NULL value, but I haven't been able to figure out how to do it with using Aura.Sql and it's underlying ExtendedPdo object.  

I've tried sending NULL, null, '', 'NULL', and PDO::PARAM_NULL but most of the time I either get type errors (e.g. trying to insert 'NULL' into a numeric cell) or zero (when using PDO::PARAM_NULL since that's the value of that constant).

Any advice?

Thanks for your time,
Dash

**Comment by pmjones** [comment]
If you could paste a code sample for what you're trying, that might help with a diagnosis.

**Comment by dashifen** [comment]
Even something as simple as the following, where $db is the database connection:

`$db->fetchAffected('INSERT INTO someTable (x, y) VALUES (:x, :y)', ["x"=>10, "y" =>PDO::PARAM_NULL]);`

Ends up inserting 0 -- which is the value of the constant, so I understand why.  But other values like null, 'NULL', and an empty string also don't actually insert a NULL into nullable columns.  

Thoughts?

**Comment by pmjones** [comment]
Aha! PDO::PARAM_NULL indicates the *type* of the param, not the *value* of the param. What happens when you try this?

```$db->fetchAffected('INSERT INTO someTable (x, y) VALUES (:x, :y)', ["x"=>10, "y" => null])```

**Comment by YaroslavMolchan** [comment]
@pmjones hello, i have same problem where try to insert `null` value, parser ignore it, I find fix but its not perfect.
I add code here: https://github.com/auraphp/Aura.Sql/blob/3.x/src/Parser/AbstractParser.php#L213
![image](https://user-images.githubusercontent.com/9335727/41042316-038e29ba-69aa-11e8-991e-775e7668f417.png)
When value is null `(array) $this->values[$this->num]` is empty and null value will be skipped.

**Comment by TheMY3** [comment]
@pmjones think I get same error last night - https://github.com/auraphp/Aura.Sql/pull/174

**Comment by dashifen** [comment]
If I use null (as in the PHP keyword), then I run into this:

`Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')`

If I `var_dump()` the values being bound into the SQL statement, they look like this:  `(3, '48', '3', )`.

The example I ran did attempt to insert into four columns.  Though, I notice now that it's creating an INSERT query that looks like this:

`INSERT INTO someTable (a, b, c, d) VALUES (?, ?, ?, ?)`

Could that be a part of it?  I can return to the functions that build the INSERT query and create better value bindings (i.e. :a, :b, :c, and :d), but it was my understanding that Aura.Sql was doing that internally.

Finally, this is on the 3.0.0-alpha1 version.  I just spent a while trying to get composer to grab the beta1 release, but it wouldn't do so.  I can update manually if you need me to, but the dependence is buried within the Domain object that I'm using so it would definitely be a hack.

**Comment by TheMY3** [comment]
@dashifen my pull request will fix it, I got same error some days ago and find solution, but need approve.

**Comment by pmjones** [comment]
Nicely done, @YaroslavMolchan .

@dashifen I have applied the fix from @YaroslavMolchan ; try out 3.x master and let me know how it goes!

**Comment by dashifen** [comment]
Awesome.  I'll check it out after work and let you know!

**Comment by TheMY3** [comment]
@dashifen can your create new release? Can`t get my changes from repo.

**Comment by dashifen** [comment]
@pmjones @YaroslavMolchan The fix worked like a charm!  Thanks so much :)

As for getting it out of the repo, I just downloaded the zip and replaced the prior version in my vendor folder.  It won't work over the long term, but once 3.0 is released, the new tag will get picked up by packagist and then composer should be able to grab it.

Thanks for your time, both of you!

**Comment by pmjones** [comment]
@dashifen @YaroslavMolchan Closing this issue as a result of the merged PR, and releasing 3.0.0 stable.

Thank you both for your work here!
