### ISSUE TITLE
Bug in Queryparser for SQLite

### ISSUE THREAD

**Issue by r4ndsen** [auraphp/Aura.Sql#183]
in sqlite a columnname containing `:` is valid, however the queryparser currently does not support this.

adjusting the `$skip` and `$split` fixed it for us

PR: https://github.com/auraphp/Aura.Sql/compare/3.x...r4ndsen:patch-2

**Comment by r4ndsen** [comment]
```php
$query = 'select "a:A", \'B:b\', `c:c`, :d from table', 
$bind = ['d' => 'foo'];
```
^ this how works, previously it was trying to bind the non-existing `:c` param

**Comment by r4ndsen** [comment]
as you can see in the example 
`"a:A"` is a string and is treated as such
`'B:b'` is a string and is treated as such
`c:c` refers to the column `c:c` directly and should not be part of the prepared statement. however this is where the bug in the query parser hits.

by adding backtick to the "specially treated characters" this problem is avoided

**Comment by harikt** [comment]
This has been fixed. Closing for now.
