### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mitmelon** [auraphp/Aura.Sql#186]
Connection Locator#

I have two database one for read and one for write...

My question is... When inserting data into the write database will the data also reflect on the read automatically. What I mean is that the data added to the write database will it also automatically add to the read database without me adding them manually.

How does the read database access the write database for view.

Awaiting your intelligent response. Thanks.

**Comment by brandonsavage** [comment]
@mitmelon You need to set up replication, which is out of the scope of this project. This project assumes you have already set up replication from write to read. 

Here's the documentation for MySQL and PostgreSQL:

https://dev.mysql.com/doc/refman/8.0/en/replication.html
https://www.postgresql.org/docs/13/runtime-config-replication.html
