### ISSUE TITLE
PHP 8.1 Compatibility 

### ISSUE THREAD

**Issue by srjlewis** [auraphp/Aura.Sql#192]
Hi

I am looking to add php 8.1 compatibility, I am thinking of using 3.x-actions branch as it has most of the phpunit updates.

I am looking to add the required typing, there are mainly 2 php RFC's that are going to caused the main problems,but I suspect there will be a few more.

1. https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg
2. https://wiki.php.net/rfc/internal_method_return_types

The first one is easy to fix.
The second has 2 approaches.

1. add the `#[ReturnTypeWillChange]` attribute, and then sort the typing out by PHP 9, i.e. kick the problem down the road, but keep BC for now.
2. add the required typing, but this will break compatibility with php version < 8.0, but will be ready for PHP 9 hopefully.

I would like to know how you would like this approaching as I am looking to do the changes?

Thanks
Steven

**Comment by kenjis** [comment]
See https://github.com/auraphp/Aura.Cli_Kernel/pull/12#issuecomment-873248524
 
-    The Aura 3.x series was for PHP 5.6 and later.
-    The Aura 4.x series is for PHP 7.2 and later.
-    I imagine a 5.x series, if you want to start one, should be for 8.0 (or perhaps 8.1?) and later.

**Comment by kenjis** [comment]
Personally, I think it would be good to set the Aura 5.x requirement to PHP 8.1 or later.

**Comment by srjlewis** [comment]
Yes I agree, 5.x should start a 8.1, as current 3.* does work fine for PHP 8.0, as PHP 8.1 is now starting to enforce typing from the core of PHP the 5.x series can now be fully typed.

If you are happy with that, I will branch from 3.x-actions as it has updates to phpUnit.

As a side note I will be having a look at aura.sqlquery and aura.sqlschema, but for the meantime they seem to be working fine with PHP 8.1 so far but not heavily tested

**Comment by kenjis** [comment]
@pmjones @harikt @koriym 
Are you okay Aura 5.x requires PHP 8.1 or later?

**Comment by pmjones** [comment]
@kenjis fine by me!

**Comment by srjlewis** [comment]
Ok I have done all the changes, everything is typed, tests have been fixed, github actions has been updated.

All test are passing local and on github actions.

I will wait for you to branch it, then make a PR to the new branch.

**Comment by kenjis** [comment]
I created `5.x` branch from `3.x-actions`.
https://github.com/auraphp/Aura.Sql/tree/5.x

It seems #191 is missing in 5.x.

**Comment by srjlewis** [comment]
I have created pull request #193 to 5.x branch
