### ISSUE TITLE
Scrutinizer Error 

### ISSUE THREAD

**Issue by kenjis** [auraphp/Aura.Sql#195]
> Waiting for External Code Coverage 
> 
> The code coverage data was not received within the specified time. Please make sure your third-party service is configured to send code coverage data.
>
> Code coverage data is not yet available.
> Code Coverage was not sent to Scrutinizer.
> Make sure that you have set-up your external service correctly.
> You can find more information on this in the documentation:
>
> https://scrutinizer-ci.com/docs/tools/external-code-coverage/
> 
> If you need help you can also email support@scrutinizer-ci.com.
> 
> https://scrutinizer-ci.com/g/auraphp/Aura.Sql/inspections/6611606a-1e89-4608-a139-3e46f11cee50

**Comment by harikt** [comment]
this has been fixed via https://github.com/auraphp/Aura.Sql/pull/206
