### ISSUE TITLE
Release note

### ISSUE THREAD

**Issue by koriym** [auraphp/Aura.Sql#205]
Hi

Currently, 4.0.0 and 5.0.0 have been tagged, but no release notes are available.
If GitHub's auto-generated release notes are good enough, they are available.

https://github.com/auraphp/Aura.Sql/releases

What do you think? It's a change from the previous format, but it's easy to create mechanically.

**Comment by pmjones** [comment]
I think it looks great! How did you do it?

**Comment by koriym** [comment]
Jus press this button!

<img width="256" alt="image" src="https://user-images.githubusercontent.com/529021/151376167-12ce2d9e-6f58-4b62-84c6-ba5bdc13fc71.png">

**Comment by koriym** [comment]
@pmjones Can I change the state from draft to publish for those? You can add any notes later.

**Comment by pmjones** [comment]
Sure -- do as you see fit, and thanks for taking care of it!

**Comment by koriym** [comment]
@brandonsavage I added release notes to the tags you created.

**Comment by koriym** [comment]
In addition, I set the default branch to the latest `5.x`.

**Comment by koriym** [comment]
@pmjones @brandonsavage Please feel free to edit them.
