### ISSUE TITLE
Abandon 4.x ?

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Sql#213]
Hi all,

We have 3.x which supports from 5.6 to 8.1 now.

4.x currently have some issues due to return types as mentioned in #194 .

5.x is using > 8.1 which supports union types, so #194 is not a problem.

Considering the return type failure ( multiple return types not handled ) for 4.x I think we should drop support for 4.x .

Thoughts ?

**Comment by iansltx** [comment]
As the person who built out 4.x to bridge between 3.x and 8.1, yeah, nuke it.

**Comment by harikt** [comment]
Thank you @iansltx . I was waiting for others reply. But seems there is no objections. So we are officially abandoning 4.x .
