### ISSUE TITLE
Consider tagging / releasing 3.0.1 please ?

### ISSUE THREAD

**Issue by ozh** [auraphp/Aura.Sql#217]
Hello there,

With ce1ac37 the 3.x branch passes tests on PHP 7.4 to 8.1, except for marginal issues opened since 2019 such as #177 and related #216. As far as I can see there is no other PR or issue regarding branch `3.x` 

Would you consider tagging and releasing at this commit ?

I'd rather use `"aura/sql": "^3"` instead of  `"aura/sql": "3.x-dev#ce1ac37"` in my `composer.json` :)

Thanks in advance

**Comment by harikt** [comment]
Sorry for being late. I missed it.

Tagged 3.1.0 . Have not merged #216 related to the issue #177 . We want to look into that bug and fix it at some point of time.

**Comment by ozh** [comment]
Thanks!
