### ISSUE TITLE
Time for 5.0.2/5.1

### ISSUE THREAD

**Issue by Qrzysio** [auraphp/Aura.Sql#225]
It might be a good idea to publish a new release 5.0.2/5.1 after recent changes and updates.

**Comment by kenjis** [comment]
It would be great if all new Aura packages are released.

**Comment by francislavoie** [comment]
@harikt can we get a new 5.x release? There's quite a few nice fixes that haven't been released yet: https://github.com/auraphp/Aura.Sql/compare/5.0.1...5.x

**Comment by harikt** [comment]
I have been busy with some personal stuffs. I will try.

**Comment by harikt** [comment]
5.0.2 released. Thank you for your patience.
