### ISSUE TITLE
Beta3 API and Doc Missing

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Sql#23]
Beta3 API and Doc Missing at http://auraphp.github.com/Aura.Sql/

**Comment by pmjones** [comment]
Yeah, I'm going to revisit this on the next release.  I'd rather not try to regenerate them now.  Thanks man.

**Comment by harikt** [comment]
@pmjones this has been fixed. I guess it was due to the `Develop` changing to `develop` worked for gh-pages. The api was created but there was rendering issues I guess. Probably I feel we should install the jekyll and parse via the release and check whether any error is there. If any error report it.  What do you think ?
