### ISSUE TITLE
SQL Limit

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Sql#31]
I am not sure whether this is related with https://bugs.php.net/bug.php?id=47960

I have not checked whether we are using something like `$stmt->bindParam(':max', $max, PDO::PARAM_INT);`

as in the http://www.php.net/manual/en/book.pdo.php#96264

```
    $text = 'SELECT * FROM posts LIMIT :lim';
    $posts = $sql->fetchAll($text, 
        [
            'lim' => $offset,
        ]
    );
```

But returns failure . So bind seems not working.

**Comment by harikt** [comment]
This is taking as string.

**Comment by pmjones** [comment]
LIMIT and OFFSET values are not bind-able at the PDO level.  They have to be passed directly, as far as I can tell.
