### ISSUE TITLE
Another setPdo() option

### ISSUE THREAD

**Issue by pmjones** [auraphp/Aura.Sql#34]
@harikt @stanlemon,

My first instinct was to try to build a PdoFactory with various strategies to allow for different ways to build and inject the PDO object.  After about two hours of trying things out, it was a bust, mostly because the ConnectionLocator really depends on the dsn-array.  Just as well; it would have been a BC break anyway.

So here's another option, using setPdo() as both of you have suggested; see the diff here:

  https://gist.github.com/4199388

This retains the `$dsn=null` default param, which allows you to construct a connection object without PDO, and then use setPdo() immediately after.  

I considered the idea of conditional checks to see if a PDO object has been injected via constructor, but I think It's just not very clean (even though it is flexible).  So that's not here.

Note that the connection factory still requires the adapter name, so that it knows what kind of connection to create (it allows a null `$dsn` as well).

What do we think about this?

-- pmj

**Comment by harikt** [comment]
Hey guys,

> This retains the $dsn=null default param, which allows you to construct a
> connection object without PDO, and then use setPdo() immediately after.

Why I don't prefer the `$dsn=null`  for if in any case assume the pdo
connection was dropped now , it will not be able to connect it again on the
stretch .

Thanks

**Comment by pmjones** [comment]
@harikt What do you suggest as an alternative?

**Comment by harikt** [comment]
@pmjones let them pass the dsn, there is nothing wrong in passing it , and also we are not promoting people to create a pdo and pass it. So I feel they need to pass dsn . Its their wish if they need to send a dummy value .

**Comment by pmjones** [comment]
That seems "off" to me, too.  There's nothing wrong, per se, but it's not right either: it's passing information that is not intended to be used.

**Comment by harikt** [comment]
one more question, also your diff is from which one?

**Comment by harikt** [comment]
`but it's not right either` I agree. Why I asked about the diff is I am not seeing the `setPdo` called in connection factory and how the pdo itself is passed to connection factory .

**Comment by pmjones** [comment]
My diff is from "develop".

As to setPdo() in the connection factory: what would have to happen is, you would create the "empty" connection, and then call setPdo() on it.  @stanlemon would that satisfy your existing use case(s) ?

**Comment by harikt** [comment]
ok, my brain doesn't work and I will be going to office shortly. So you can go for it :+1: .

**Comment by stanlemon** [comment]
@pmjones Yes, this works for my use-case. This would allow me to substitute an existing Pdo connection w/o supply dummy dsn data or having to carry over the original dsn data.

FWIW: I think this is a highly advantageous change - it allows for applications w/ existing frameworks to progressively migrate over to using Aura.Sql w/o having to juggle multiple database connections.

**Comment by pmjones** [comment]
Implemented by:

https://github.com/auraphp/Aura.Sql/commit/d0e337bf2099d0bd860977de3256d2848a1d030c

**Comment by pmjones** [comment]
And I agree, it's a good change.  Thanks @stanlemon for the report!
