### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Sql#37]
Hey @pmjones , 

Do you think we can release ~~2.0.1~~ `1.0.1` or ~~2.1~~ `1.1` for the Aura.Sql with the new features?

**Comment by pmjones** [comment]
We only need a 2.x if we make severe BC breaks.  Adding new major features is a 1.x release :-)

**Comment by harikt** [comment]
aah sorry I mean 1.0.1  :) .

**Comment by pmjones** [comment]
Sure; when we start the next release cycle we'll update the version.

**Comment by harikt** [comment]
no, I was asking for a quicker release when we did BC breaks. That helps people to upgrade only once. Else they want to do many times :-1:  .
