### ISSUE TITLE
When no options passed

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Sql#4]
When the $options not passed as array 

```
$di->params['Aura\Sql\ConnectionManager'] = array(
    'factory' => $di->lazyNew('Aura\Sql\ConnectionFactory'),
    'default' => array(
        'adapter'  => 'mysql',
        'dsn'      => array(
            'host' => 'localhost',
            'dbname' => 'auradb',
        ),
        'username' => 'monty',
        'password' => 'some_pass',
        //'options' => array(),
    ),
);
```

the error is getting 

Notice: Undefined index: options in /media/Linux/aurasystem/package/Aura.Sql/src/ConnectionManager.php on line 129 Catchable fatal error: Argument 4 passed to Aura\Sql\Connection\AbstractConnection::__construct() must be an array, null given in /media/Linux/aurasystem/package/Aura.Sql/src/Connection/AbstractConnection.php on line 31 

When closely looking the $merge is not working as expected . A print_r( $merged ) will see what values it has . The options is undefined . A quick and dirty fix is 

```
protected function mergeAdapterParams(array $override = array())
{
    $merged  = $this->merge($this->default, $override);
    $adapter = $merged['adapter'];
    /*
     * if no options passed by defaut the options should be an array
     * Currently the merge not working as expected. And the options is undefined .
     * A quick and dirty fix is pass in configs default as options => array()
     * or fixing like the one below
     */
    if(! isset($merged['options']) ) {
        $merged['options'] = array();
    }
    $params  = array(
        'dsn'      => $merged['dsn'],
        'username' => $merged['username'],
        'password' => $merged['password'],
        'options'  => $merged['options'],
    );

    return array($adapter, $params);
}
```

Still some other issue :( to make a connection , looking .

**Comment by pmjones** [comment]
harikt -- is this still a problem?

**Comment by harikt** [comment]
@pmjones I have not tested it recently . Will look tomorrow or in the weekend .

**Comment by harikt** [comment]
As the signature changes and default `options` contains an array which is empty has solved the issue

```
public function newInstance(
    $name,
    $dsn,
    $username = null,
    $password = null,
    $options = []
)
```

For those who are new the example above will not work as of the changes made, so please look documentation or create a new issue if you have.
