### ISSUE TITLE
Checking for property at the Column class

### ISSUE THREAD

**Issue by ghost** [auraphp/Aura.Sql#40]
When using Twig and trying to access a Column property, it gives an error saying that the method doesn't exists.

For example, if you try to access the column name property:

col.name

It halts saying the method name() doesn't exists.
It can be fixed by just putting an __isset($key) checking if $key is a class property.

Thanks!

**Comment by pmjones** [comment]
Good call. Can you place a pull request so I don't forget?

**Comment by ghost** [comment]
Ok. I'll do it tomorrow.
Thanks!
