### ISSUE TITLE
Query builder orWhere

### ISSUE THREAD

**Issue by ghost** [auraphp/Aura.Sql#45]
When using the orWhere() method of the Select query builder, parethesis () are not put around the where conditions, making the query result inconsistent.

There are some ways to solve it, like adding a method to open and close the OR condition, or maybe trying to detect the orWhere begin and end.

If you need some help to do it or test, msg me back.

**Comment by pmjones** [comment]
Hi @ramirovjr -- adding an OR is a natural "break" in precedence; it would be presumptive to add parentheses on behalf of the user. If needed, you might try adding an open paren in one WHERE condition and a closing paren in a later WHERE condition.  Having said that, if you still feel the query builder should do this automatically, I'd be happy to review and discuss any pull request you submit.

**Comment by ghost** [comment]
Your solution seens to solve the problem too, haven't thought about it.
I think that a simple documentation fix solves the bug, do you agree?
If you still want a patch, I can build it and we talk more about it.

**Comment by harikt** [comment]
@ramirovjr PR are always welcome, don't ask whether we need a PR or not ;) . Give it . 

Thank you.

**Comment by pmjones** [comment]
I think we're good here. @ramirovjr if you want to write up a patch to the docs, that's fine with me.  Thanks!
