### ISSUE TITLE
Non-standard SQL features

### ISSUE THREAD

**Issue by MAXakaWIZARD** [auraphp/Aura.Sql#46]
For instance MySQL supports 
UPDATE tbl 
SET a = 1 
WHERE b = 2 
LIMIT 5
Limit part is non-standard, but I need it in \Aura\Sql\Query\Update.
Same with SELECT SQL_CALC_FOUND_ROWS etc.
Can I send pull requests regarding those features or Aura\Query objects should support only standard syntax?

**Comment by pmjones** [comment]
Hi Max -- that's a good question. It occurs to me now that we could have a class MysqlUpdate that extends Update and adds the non-standard stuff. Would you be interested in sending a PR doing something like that?

**Comment by MAXakaWIZARD** [comment]
Yep, sure!

**Comment by pmjones** [comment]
Looks like #47 deals with this.
