### ISSUE TITLE
lastInsertId returns 0

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Sql#5]
Working with MySQL in Ubuntu .

lastInsertId() returns 0 . 

Have a look into http://www.php.net/manual/en/pdo.lastinsertid.php#85129 , also have a look into postgre's

http://www.php.net/manual/en/pdo.lastinsertid.php#86591

So lastInsertId seems not reliable .

```
Note from php.net :

This method may not return a meaningful or consistent result across different PDO drivers, because the underlying database may not even support the notion of auto-increment fields or sequences.
```

**Comment by pmjones** [comment]
harikt -- is this still a problem?

**Comment by harikt** [comment]
@pmjones I guess no , as we moved out to its own adapters. I can test this in weekend only :( .

**Comment by harikt** [comment]
For mysql this works, I don't know the case for postgre nor sqlite for I don't have both for now . If there is any issues let them open it :-) .
