### ISSUE TITLE
DriverFactory and Select

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Sql#6]
Did you missed to add `DriverFactory` ?
Its still mentioning at `scripts/instance.php` .
Also the `use Aura\Sql\Select;`

**Comment by pmjones** [comment]
Ah, thanks for pointing out `instance.php`. I don't know if DriverFactory is going to make it in; to have that, we need Aura.Di, and I want to keep the dependencies at zero.  Might be a way to do it without the DI package.

**Comment by pmjones** [comment]
So, AdapterFactory is back in place, but I'm going to leave out the Select object for the first release (it's a lot of work to get it going).  Anything else on this issue?

**Comment by harikt** [comment]
no for now I don't have anything :)

**Comment by harikt** [comment]
In config/default.php , I am not sure why you didn't add

```
use Aura\Sql\AdapterFactory;
$adapter_factory = new AdapterFactory;
$sql = $adapter_factory->newInstance();
```

Or you missed it ? 
I guess you may have thought if the user needs let them add.

**Comment by pmjones** [comment]
I think I'm going to leave that out of config/default.php, at least for now. It makes more sense to have the DI service be the connection manager, rather than the adapter factory.  (Going to try to add the connection manager to the SQL package, but at worst it will be in the Framework package.)

**Comment by harikt** [comment]
Why not bring it here itself . If people love to use the Aura.Di let them use connection manager , else the same as above ?

**Comment by harikt** [comment]
Anything to add over here ? Close it ?

**Comment by pmjones** [comment]
Yeah, this seems like it's been taken care of. Thanks!
