### ISSUE TITLE
Array quoting of placeholders for empty arrays

### ISSUE THREAD

**Issue by stof** [auraphp/Aura.Sql#60]
In case of an empty array being bound inside a `IN(?)`, it will generate `WHERE name IN()`, which is a syntax error

**Comment by pmjones** [comment]
I think that's the correct behavior; there's nothing to quote, after all. What do you suggest?

**Comment by stof** [comment]
@pmjones The issue is that you are making it transparent to use an array, except for 1 case (which might happen but stay unnoticed when the array is dynamic). For a condition `WHERE name IN(?)` with an empty array, I would except an empty result set, not a PDOException.
Doctrine DBAL is preparing the statement as `IN (NULL)`, which will produce the expected behavior in case of a positive `IN()` (being always falsy so rejecting everything). there is still one drawback with this code, when using `WHERE a NOT IN(NULL)`, as `NOT IN(NULL)` will also be falsy (`IN(NULL)` will return `NULL` like for all other SQL operators, and negating `NULL` is still `NULL`)

**Comment by pmjones** [comment]
So what are you advocating for here?

**Comment by pmjones** [comment]
(closed by accident sorry)

**Comment by stof** [comment]
@pmjones well, the best solution could be to figure a way to have a false condition instead of a `NULL` one. It may be a bit difficult.

In the meantime, the exception would be really confusing as it would be caused by some modification done by Aura while preparing the query (the user would never find `IN()` in his code).
The other solution would be to throw the exception earlier when binding the value, where you can give a better exception message explaining that binding an empty array is not supported by Aura.Sql. This way, the user would understand the error.

**Comment by pmjones** [comment]
It sounds like the solution easiest to implement would be an exception thrown when quoting an empty array for a bound value. Do you agree with that, or would you prefer something else? (As always, if you have a patch or pull request, I'm happy to review.)

**Comment by pmjones** [comment]
(As a side note, it is not the job of the quoting mechanism to build syntactically correct statements; that's up to the developer.)

**Comment by harikt** [comment]
Thank you @stof for the bug report.

Reading all the comments first I thought it will be good to document and add an exception. Looking at how adminer ( by @vrana ) was working when I don't pass any values it worked as @stof mentioning https://github.com/auraphp/Aura.Sql/issues/60#issuecomment-26747976 . 

This is a serious case for it is not working as expected though we pass NULL .
We are passing an entirely wrong values and getting wrong values for things like `IS NULL` should apply . Eg : a field with `something` can have `NULL` and may be having values of `1, 2, 3` . In this case `IN NULL` results should return some values. ( ie also someone will expect )

**Comment by stof** [comment]
@harikt `IN(NULL)` **always** returns `NULL` (and so is falsy), at least in MySQL. the only operator allowing to check NULL fields is `IS`, not `IN`

**Comment by harikt** [comment]
yes that is what I also mean. So doesn't that mean we are altering the query.

**Comment by pmjones** [comment]
@stof To reiterate an earlier question: It sounds like the solution easiest to implement would be an exception thrown when quoting an empty array for a bound value. Do you agree with that, or would you prefer something else? (As always, if you have a patch or pull request, I'm happy to review.)

**Comment by stof** [comment]
@pmjones I think it is fine. It gives a clear error to the user at least. Note that I don't care much about the solution you choose as I don't use Aura.SQL in my projects anyway. I reported the issue because I looked at the package when you announced its v2 and I saw this issue which was faced by Doctrine a few months ago.

**Comment by pmjones** [comment]
I appreciate you taking the time to report it, even as a non-user. Thanks!

**Comment by harikt** [comment]
Thank you @stof for reporting it. Your attitude is highly appreciated.

**Comment by Koc** [comment]
-1. We shouldn't even make query for an empty set.

**Comment by stof** [comment]
@Koc -1 on what ? The latest agreement here is to throw a meaningful exception instead of letting PDO failing with a SQL syntax error, so that users understand their mistake

**Comment by Koc** [comment]
-1 on adding `IN(NULL)` by default.
