### ISSUE TITLE
Check placeholders parser

### ISSUE THREAD

**Issue by Koc** [auraphp/Aura.Sql#62]
I'm porting you parser to my library for sphinxsearch query builder and noticed that queries like `'SELECT :foo'` not processed properly because placeholder on the end of the string.

**Comment by pmjones** [comment]
Hi @Koc -- if you have a code example, or a fix, that would help resolve the issue.

**Comment by Koc** [comment]
I can update test case by adding test scenario. Where can I find tests for the https://github.com/auraphp/Aura.Sql/blob/1e97ff20bf0ca475f8e08ded2ee342e3c08fcd7a/src/Aura/Sql/Connection/AbstractConnection.php#L442 ?

**Comment by harikt** [comment]
@pmjones this needs to be addressed.
@Koc I assume you need to split that to write a test.
Sorry for the delay and Thank you for the patience.

**Comment by harikt** [comment]
@Koc I assume https://github.com/auraphp/Aura.Sql/blob/a9b9cd77291fd3f4858d42fb02d03e9ddc2efb59/tests/src/AbstractExtendedPdoTest.php#L504 is the test .

Were you able to resolve this?

Thank you
