### ISSUE TITLE
Sub-transactions

### ISSUE THREAD

**Issue by mindplay-dk** [auraphp/Aura.Sql#66]
Here's a custom extension I'm using:

```
class Connection extends ExtendedPdo
{
    /**
     * @var int number of nested calls to transact()
     * @see transact()
     */
    private $transaction_level = 0;

    /**
     * @var bool net result of nested calls to transact()
     * @see transact()
     */
    private $transaction_result;

    /**
     * @param callable $func function to call; must return TRUE to commit or FALSE to roll back
     *
     * @return bool TRUE on success (committed) or FALSE on failure (rolled back)
     *
     * @throws InvalidArgumentException if the provided argument is not a callable function
     * @throws LogicException if an unhandled Exception occurs while calling the provided function
     * @throws UnexpectedValueException if the provided function does not return TRUE or FALSE
     */
    public function transact($func)
    {
        if (! is_callable($func)) {
            throw new InvalidArgumentException("invalid argument: \$func is not callable");
        }

        if ($this->transaction_level === 0) {
            // starting a new stack of transactions - assume success:
            $this->beginTransaction();
            $this->transaction_result = true;
        }

        $this->transaction_level += 1;

        $commit = false; // assume roll back

        try {
            $commit = call_user_func($func);
        } catch (Exception $exception) {
            $commit = false;
        }

        $this->transaction_result = (bool) $commit && $this->transaction_result;

        $this->transaction_level -= 1;

        if ($this->transaction_level === 0 && $this->transaction_result === true) {
            $this->commit();
            return true; // the net transaction is a success!
        }

        if ($this->transaction_result === false) {
            $this->rollBack();
        }

        if (isset($exception)) {
            // re-throw an unhandled Exception:
            throw new LogicException("unhandled Exception during transaction", 0, $exception);
        }

        if (! is_bool($commit)) {
            throw new UnexpectedValueException("\$func must return TRUE (to commit) or FALSE (to roll back)");
        }

        return $this->transaction_result;
    }
}
```

This new method will track sub-transactions, so you can do something like this:

```
$connection->transact(function() {
    return true; // commits the transaction (false would roll back the transaction)
});
```

This eliminates the need to synchronize calls to `beginTransaction()` and `commit()` or `rollBack()` and instead performs transactions "transactionally", heh ;-)

An important point here, is that nested calls to `transact()` will be counted, and if _any_ nested call returns false (or throws an exception) the _entire_ transaction will correctly roll back.

If it were up to me, there wouldn't _be_ any other way to perform transactions - having to call begin/commit/rollback individually is semantically "broken", since it does resemble a transaction or guarantee (the only correct) execution order.

This is fully unit-tested and works. Let me know if you're interested in integrating this?

**Comment by mindplay-dk** [comment]
You ever look at this? Just wondering.

**Comment by pmjones** [comment]
(/me furrows brow) I recall looking at it, and thought I commented on closing it. I recall my comment being along the lines of, "Do the underlying engine support nested transaction natively? Do they permit rolling back to the last sub-transaction?" (I recall having other notes, but not what they were.)

**Comment by mindplay-dk** [comment]
> Do the underlying engine support nested transaction natively?

They don't, or at least MySQL doesn't - that's sort of the point; it counts the transaction level, so that calls to `transact()`, during a previous call to `transact()`, does not lead to early commits. All nested calls to `transact()` need to succeed (return true) in order for the transaction to commit.

The main point though, is to achieve transaction semantics - as opposed to manually having to check conditions and call commit or rollback, potentially breaking semantics (by forgetting to commit or rollback) or forgetting to manually check `inTransaction()`, etc... That stuff gets wonky.

I've been doing it this way for a long time, on lots of projects, and it saved me a lot of headache.

**Comment by pmjones** [comment]
> They don't, or at least MySQL doesn't 

(/me nods)

So SAVEPOINT and RELEASE (etc) don't quite do the trick for you? A brief googling revealed support in mysql, sqlite, pgsql, and sql server, though I don't know how recently.

**Comment by mindplay-dk** [comment]
AFAIK, in MySql this is supported by INNO only, but yes - you could use
that for sub transactions where available maybe, though that would give it
a very different meaning depending on the database.

I've never personally needed savepoints. I need transactions all the time,
and I don't like the non-transactional API most database APIs provide, so I
usually add in something like this. YMMV.
