### ISSUE TITLE
Add HHVM back as a build target

### ISSUE THREAD

**Issue by jklein** [auraphp/Aura.Sql#72]
It looks like the issue that previously blocked its usage has been fixed:

https://github.com/facebook/hhvm/issues/1560

There might be other blockers, but it's worth trying again IMO.

**Comment by harikt** [comment]
Sorry it is still not yet fixed at travis https://travis-ci.org/harikt/Aura.Sql/jobs/23688419 . Probably once they update to latest we can add.

**Comment by jklein** [comment]
Okay fair enough, thanks for trying!

**Comment by harikt** [comment]
We will open once travis is with the new version. And you are welcome. Next time you can open the PR and we will see whether we can merge or not ;) .

**Comment by iansltx** [comment]
Just noticed that Travis is running against 3.1 now. Maybe worthwhile to start testing against HHVM again?

**Comment by harikt** [comment]
@iansltx still failing https://travis-ci.org/auraphp/Aura.Sql/jobs/23688453

**Comment by iansltx** [comment]
Looks like the issue is here:

https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/ext_pdo.cpp#L755

and Docctrine worked around it here:

https://github.com/doctrine/dbal/pull/495

I may have a workaround for this though...

**Comment by harikt** [comment]
@iansltx come with a fix, we will merge :+1:  .

Thank you.

**Comment by iansltx** [comment]
50/50 that this will be labelled as wontfix, but here goes nothing:

https://github.com/facebook/hhvm/issues/3041
