### ISSUE TITLE
Sequential params on execution queries should be 0-indexed

### ISSUE THREAD

**Issue by iansltx** [auraphp/Aura.Sql#75]
Currently, fetch*(), perform(), etc. assume a 1-indexed array when dealing with non-named (question-mark) params. The base PDO execute() uses a 0-indexed array. This results in inconsistent behavior between ExtendedPDO and PDO, forcing workarounds like

https://gist.github.com/iansltx/6d0181c835e5afbf2965#file-gistfile1-php-L6

(I feed those results into fetchOne() or fetchAll() depending on whether I'm counting or retrieving results).

It sounds like the inconsistency here is because http://www.php.net//manual/en/pdostatement.bindvalue.php uses a 1-indexed array and http://www.php.net/manual/en/pdostatement.execute.php uses a 0-indexed array, when interacting with non-named params. php.net docs need an edit to clarify that this is what's going on on the execute site, but the editor isn't playing nice with me right now.

Fixing this issue will be backwards incompatible with the hack posted above, though for folks who've used 1-indexed as input instead and have a properly sized array it'd be possible to keep their implementations working.

**Comment by harikt** [comment]
Question can we do a hack with using `array_unshift` if the keys are `0`

**Comment by iansltx** [comment]
Sounds like that would work.

**Comment by harikt** [comment]
cool. @iansltx write failing tests and keep a patch and send a PR if you have some time.

Thanks.
