### ISSUE TITLE
A way to debug errors in Query Easily

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Sql#8]
Hi , 
I just had a thought that when we do via PDO , there are possibilities that the query can fail . 

And was looking through some of the articles like 

http://stackoverflow.com/questions/2411182/how-to-debug-pdo-database-queries

http://daveyshafik.com/archives/605-debugging-pdo-prepared-statements.html

http://php.net/manual/en/pdostatement.debugdumpparams.php

Do you have any thoughts on this to make it easy for developers to track the issue ?

**Comment by pmjones** [comment]
We kind of do this now with the profiler/logger.  When the profiler is turned on, it captures the query text, the data bound to the query, the elapsed time, and (something i really like) a debug backtrace so you can see exactly where the query came from in the codebase.  Is that sufficient?

**Comment by harikt** [comment]
When profiler is active , yes we get the query like the one below .

```
foreach($sql->getProfiler()->getProfiles() as $i => $profile ) {
    echo "Query : " . ($i+1) . "  " . $profile->text . " took " . $profile->time . PHP_EOL;
    //print_r( $profile->trace );
}

Query : 2  SELECT * FROM posts took 0.00012612342834473
Query : 3  SELECT * FROM posts Where id = :id took 0.00043177604675293
Query : 4  INSERT INTO `posts`(`title`, `author_id`, `body`) VALUES (:title, :author_id, :body) took 0.050559043884277
```

Problems are which I love to improve when profiler is setActive are : 

1 ) You can see we cannot directly copy and paste the code and do a query some where .

So the query

```
  SELECT * FROM posts Where id = :id
```

 will become 

```
  SELECT * FROM posts Where id = 1
```

something like that.

2 ) Debug backtrace is an array of recursion. So when we do a print for it, that will be hard to trace it out . Is there an easy way ? May be I am missing all the functionality .
