### ISSUE TITLE
Documentation doesn't discuss upgrading from 1.x version

### ISSUE THREAD

**Issue by brandonsavage** [auraphp/Aura.Sql#81]
The documentation should discuss the major change points between 1.x and 2.x, namely the separation of the ORM concerns into a separate library.

**Comment by pmjones** [comment]
Sorry, swamped as it is. Closing this, unless someone else wants to write up a set of change notes. :-/

**Comment by brandonsavage** [comment]
Does closing this make sense? I filed it because it's needed even if no one has time to write it right now. If we close it we don't recognize that it's missing.
