### ISSUE TITLE
New release / tag

### ISSUE THREAD

**Issue by frederikbosch** [auraphp/Aura.Sql#88]
Could you release a new version of Aura.Sql? I am specifically interested in the extraction of the Rebuilder since I already have own methods for direct fetching. Thanks for the wonderful work.

**Comment by pmjones** [comment]
HI @frederikbosch -- I think it's fair to expect a new release over the weekend. Thanks for the nudge!

**Comment by frederikbosch** [comment]
@pmjones Thank you for the update! Looking forward to the release and using Aura.Sql.

**Comment by pmjones** [comment]
Granted! https://github.com/auraphp/Aura.Sql/releases/tag/2.2.0

**Comment by harikt** [comment]
:+1:
