### ISSUE TITLE
First parameter cannot be null when using perform/rebuilder

### ISSUE THREAD

**Issue by frederikbosch** [auraphp/Aura.Sql#96]
If the first parameter of a query with numbered placeholders is null, you will get an undefined offset in Rebuilder.php on line 220. The standard PDO library allows the first parameter to be null.

The following code generates the error.

``` php
$pdo->perform('SELECT * FROM test WHERE column_one = ?', [null]);
```

**Comment by pmjones** [comment]
Fixed by #97
