### ISSUE TITLE
Profiler documentation improvement request

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Sql#99]
It'd be nice in the README.md to mention that there are likely to be multiple profile entries in the array, numerically indexed, even if only one query has been issued.  In my recent experience, I get 2 such entries for my query, both effectively identical, except the second entry actually contains the bind values and the first does not (empty array).

**Comment by cxj** [comment]
I'll be happy to write the suggested improvements once I fully understand what's going on.  I used var_dump() to figure out where things were, but don't grok the "why" yet.

**Comment by harikt** [comment]
I confirm I too got 2 queries. Was using with Aura.SqlMapper . I will look into this.

**Comment by harikt** [comment]
Hey , 

So I figured out where this was happening. But I don't know a right way.
Here is what I did to understand

``` php
$profiles = $pdo->getProfiler()->getProfiles();
foreach ($profiles as $profile) {
    echo $profile['statement'] . PHP_EOL;
    echo $profile['function'] . PHP_EOL;
    echo var_export($profile['bind_values'], true) . PHP_EOL;
}
```

You can see the calls of functions are to `perform` and `prepare`. Which both are profiling, may be there should be a flag to profile only one ? or may be let's leave it as it is for this is just a debugging tool, and mention the same in the docs?

**Comment by cxj** [comment]
I would be happy with clear and accurate documentation on how it behaves.  Maybe it is the case that a profile entry is made with each PDO call?

**Comment by harikt** [comment]
Basically to every function it has.

**Comment by pmjones** [comment]
I think that's a good idea @cxj . You want to write something up?

**Comment by cxj** [comment]
I'll give it a shot.

**Comment by harikt** [comment]
Closing this for this was addressed in https://github.com/auraphp/Aura.Sql/pull/103 . 

@cxj in case it is not completely address we can re-open.

Thank you
